### ISSUE TITLE
Running claircli inside a docker container [Question]

### ISSUE THREAD

**Issue by Naman1997** [joelee2012/claircli#14]
Hey, i've been trying to get claircli to run inside a container.
My docker compose :
```
version: '2'
services:
  app:
    container_name: zapper
    restart: always
    build: . #Build from git repo
    links:
      - clair
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    image: zap #Image name for Dynamic Analysis repo

  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
```

Command used inside the zapper container:
`claircli -c http://clair:6060 -f json -l #HOST_IP namanarora/java-mongo-crud_app:latest`

Output:
`2020-02-27 11:37:51,801|INFO|Starting local http server
2020-02-27 11:37:51,802|INFO|Local http server serving at port: 12290
2020-02-27 11:37:51,803|INFO|*****************************1******************************
2020-02-27 11:37:51,803|INFO|Analyzing <Image: namanarora/java-mongo-crud_app:latest>
2020-02-27 11:37:51,805|WARNING|('Connection aborted.', error(2, 'No such file or directory'))
2020-02-27 11:37:51,805|INFO|============================================================
2020-02-27 11:37:51,805|INFO|            CLAIR ANALYSIS REPORTS: (1) IN TOTAL            
2020-02-27 11:37:51,805|INFO|============================================================
2020-02-27 11:37:51,806|ERROR|IMAGES WERE ANALYZED WITH ERROR (1)
2020-02-27 11:37:51,806|ERROR|namanarora/java-mongo-crud_app:latest
`
Since I had already shared the docker.sock via volumes, I was expecting it to use that to get image values. How can I fix this?
